### ISSUE TITLE
Having trouble in understanding the data format

### ISSUE THREAD

**Issue by empty-id** [cynricfu/MAGNN#10]
Hi, I tried to dive into the source code of load_DBLP_data() function and print the intermediate variables. However, I still have trouble in understanding the data format. Could you give some explanation? Thank you!

**Comment by cynricfu** [comment]
Each pickle file stores the metapath instances of a specific metapath. E.g., "0-1-0_idx.pickle" stores metapath instances for metapath 0-1-0 (i.e., author-paper-author). The metapath instances are grouped based on the starting nodes.
Each adjlist file stores the node pairs constructed by the ending nodes of the metapath instances. E.g., if there is a metapath instance 700-805-1000, then we would have the node pair (700, 1000) in adjlist.
Others should be relatively simple to understand.

**Comment by empty-id** [comment]
Thank you!

**Comment by null-id** [comment]
Hi @cynricfu , I understand the pickle file now. But I am still confused about the format of adjlist file. Sorry for disturbing you again, but could you give me an example? For example, what these three lines mean?

```
0 0 0
1 1 1 1 1 1 1 1 1 1 1 5
2 2 2 2 1183 1183 2353 2353 3626
```
