### ISSUE TITLE
Metapath instances sampling

### ISSUE THREAD

**Issue by siyongxu** [cynricfu/MAGNN#11]
Hi , I need to use your sampling code in preprocess.py, and I want to know how long it takes to sample all the metapath instances for dblp dataset? I have run it on an adjM for a long time so that I‘m a little worried that I made something wrong.

**Comment by siyongxu** [comment]
It's okay.I have finished with it.

**Comment by cynricfu** [comment]
The preprocessing time is relatively long for DBLP.
But I guess it would be simple and straightforward to accelerate the code by applying multiprocessing.

**Comment by siyongxu** [comment]
Thanks for your reply!

**Comment by xhyuaner** [comment]
May I ask how long it took for you to successfully run it? How many hours or how many days?   Do you use multiprocessing? @siyongxu
