### ISSUE TITLE
Improvement Idea using Pretrained BERT word embedding model

### ISSUE THREAD

**Issue by myeonghak** [cynricfu/MAGNN#12]
Hi, I am recently studying graph neural networks, and was looking for some SOTA implementations using GNN.

From paperswithcode I got to know your work and got really impressed by your brilliant solutions to the problems that previous literature had.

Trying on my own using your IMDB codes, I came up with the idea of implementing a pre-trained embedding model to improve prediction performance.

so I used a pre-trained DistillBERT model to make node features instead of count vector, and the below is what I got as a result.

[DistillBERT]

SVM test
Macro-F1: 0.640466 ~ 0.014346 (0.8), 0.642629 ~ 0.007654 (0.6), 0.638584 ~ 0.005989 (0.4), 0.632471 ~ 0.004478 (0.2)
Micro-F1: 0.640230 ~ 0.014154 (0.8), 0.642098 ~ 0.007682 (0.6), 0.637949 ~ 0.006281 (0.4), 0.631836 ~ 0.004786 (0.2)
K-means test
NMI: 0.174531 ~ 0.000000
ARI: 0.162560 ~ 0.000000
----------------------------------------------------------------
SVM tests summary
Macro-F1: 0.640466 ~ 0.014346 (0.8), 0.642629 ~ 0.007654 (0.6), 0.638584 ~ 0.005989 (0.4), 0.632471 ~ 0.004478 (0.2)
Micro-F1: 0.640230 ~ 0.014154 (0.8), 0.642098 ~ 0.007682 (0.6), 0.637949 ~ 0.006281 (0.4), 0.631836 ~ 0.004786 (0.2)
K-means tests summary
NMI: 0.174531 ~ 0.000000
ARI: 0.162560 ~ 0.000000

and below is the original result I got when I ran the code.

[original result]

SVM test
Macro-F1: 0.601211 ~ 0.016628 (0.8), 0.602220 ~ 0.007302 (0.6), 0.598148 ~ 0.010544 (0.4), 0.591385 ~ 0.004841 (0.2)
Micro-F1: 0.600718 ~ 0.016712 (0.8), 0.602011 ~ 0.007650 (0.6), 0.598323 ~ 0.010250 (0.4), 0.591484 ~ 0.004161 (0.2)
K-means test
NMI: 0.151366 ~ 0.000000
ARI: 0.159534 ~ 0.000000
----------------------------------------------------------------
SVM tests summary
Macro-F1: 0.601211 ~ 0.016628 (0.8), 0.602220 ~ 0.007302 (0.6), 0.598148 ~ 0.010544 (0.4), 0.591385 ~ 0.004841 (0.2)
Micro-F1: 0.600718 ~ 0.016712 (0.8), 0.602011 ~ 0.007650 (0.6), 0.598323 ~ 0.010250 (0.4), 0.591484 ~ 0.004161 (0.2)
K-means tests summary
NMI: 0.151366 ~ 0.000000
ARI: 0.159534 ~ 0.000000

I think you might have known about this approach, but I just wanted to let you know this!

If you are interested, I'll provide the full code to you so you could refer.

Thanks again for this wonderful paper and the implementation codes.

Mattias

**Comment by cynricfu** [comment]
Good to know that there is a significant boost of performance by replacing the bag-of-words representations with the DistillBERT-encoded features. This makes sense as DistillBERT should be a better model for language as compared to bag-of-words.
If you can, please share with me your implementation, it may help my future research.
If you want, you can also upload it to a repo and share it publicly

**Comment by myeonghak** [comment]
Really glad to let you know the result and glad that you commented on it. 

Yes, I will share my implementation with you very soon as long as I have some time to organize it!

And thank you for letting me upload it. :) 👍

**Comment by myeonghak** [comment]
Hi, sorry for being late.
I tried my best to make the result I showed above reproducible,
I couldn't make it.

1) I got the result above in colab notebook, but whenever I try to rerun the notebook, the session crashed for some reason. 
after trying several sessions to debug the problem, I had to work on my own work.

2) After a while I tried it again yesterday and I found no error running the notebook, but strangely the result wasn't so good. there was an improvement but not that much as I showed above (ex. macro-F1 0.64~), or in some trials the performance was worse than the original result. it's against my expectation and I have no idea why this happens. the only guess I can make is that the good result I got was a kind of coincidence, but I am kind of confused.

I wanted to give you a good result and tidy codes, but I am sorry that I couldn't make it.
the codes I used are in my repository "MAGNN+BERT" and as you might discover, the only change I made was to add a part of code to convert genre tokens to distilBERT embedding vectors.

I will keep experiments on my own, and I hope this can help your future work in some way.
As soon as I find a reason for the result, I will let you know.

thanks again and please let me know if you have any ideas or questions.
