### ISSUE TITLE
Link prediction

### ISSUE THREAD

**Issue by siyongxu** [cynricfu/MAGNN#13]
In link prediiction experiments, should parameters be shared in MAGNN_ctr_ntype_specific if the target nodes are the same type?

**Comment by cynricfu** [comment]
For each metapath (i.e., `MAGNN_metapath_specific`), it has its own set of parameters, except for the relation vectors `r_vec` used for the relational rotation metapath encoder, which is unique and shared by all layers and modules.

**Comment by siyongxu** [comment]
Hi, what I mean is that in MAGNN_lp_layer, parameters of user and item part are not shared because user and item are not the same type. However, should they shared if two target node are the same type such as user and user? It seems to be correct because they are symmetric in MAGNN‘s unsupervised loss.

![image](https://user-images.githubusercontent.com/38311056/98251970-62f91f00-1fb4-11eb-886c-726881a32e2f.png)

**Comment by cynricfu** [comment]
Oh, I misunderstood your question.
Yes, if the node type is the same for the two end nodes of the links you want to predict, then the parameters should be shared (or just use one `MAGNN_ctr_ntype_specific` for both ends).
My `MAGNN_lp_layer` did not consider this case. It needs to be adjusted for your mentioned scenario.

**Comment by siyongxu** [comment]
Oh,yeah.Thanks for your reply. I've goi it.
