### ISSUE TITLE
About Data Preprocessing

### ISSUE THREAD

**Issue by empty-id** [cynricfu/MAGNN#15]
Hi, I have a question about the preprocessing in DBLP.

As I see that in the ```preprocess_DBLP.ipynb```, you use ```data/raw/DBLP/DBLP4057_GAT_with_idx.mat``` from HAN.

Where could I find that file? And how to promise the corresponding index of that matrix is same with your data accordingly?

**Comment by cynricfu** [comment]
`DBLP4057_GAT_with_idx.mat` is obtained from [HAN's official repo](https://github.com/Jhy1993/HAN#Datasets). Specifically, [this Baidu Wangpan link](https://pan.baidu.com/s/1Qr2e97MofXsBhUvQqgJqDg) with access code `6b3h`.

As of the index correspondence, I have verified it by comparing the labels from the `DBLP4057_GAT_with_idx.mat` file and the labels from the `author_label.txt` file. They are the same.

**Comment by empty-id** [comment]
Yeah, I get it. Thank you!
