### ISSUE TITLE
What does etypes_list variable mean?

### ISSUE THREAD

**Issue by empty-id** [cynricfu/MAGNN#16]
such as ```[[0,1], [0,2,3,1], [0,4,5,1]]``` in the run_DBLP.py

If I want to run MAGNN on a new dataset. How should I set the etypes_list value?

**Comment by cynricfu** [comment]
Please refer to this issue: #5

**Comment by empty-id** [comment]
So, if I run the code on a new dataset. How can I get access to which id means which edge type?

**Comment by cynricfu** [comment]
The index correspondence of the edge types is determined by yourself during the data preprocessing.

**Comment by aniruddhamx2020** [comment]
> The index correspondence of the edge types is determined by yourself during the data preprocessing.

Hi,
1. Where exactly in the 'preprocess_IMPDB.ipynb' the e-types are defined?
2. In 'run_IMDB.py', what is the logic behind the construction of etypes_lists (order of edge type, list of lists etc.)?

I'm trying to replicate the IMDB script for new data.
