### ISSUE TITLE
How to deal with nodes with no neighbor for a given metapath?

### ISSUE THREAD

**Issue by empty-id** [cynricfu/MAGNN#17]
I face the error when I run my own dataset:

```
Traceback (most recent call last):
  File "run_mydata.py", line 223, in <module>
    args.epoch, args.patience, args.batch_size, args.samples, args.repeat, args.save_postfix)
  File "run_mydata.py", line 96, in run_model_DBLP
    adjlists, edge_metapath_indices_list, train_idx_batch, device, neighbor_samples)
  File "/MAGNN-master/utils/tools.py", line 112, in parse_minibatch
    [adjlist[i] for i in idx_batch], [indices[i] for i in idx_batch], samples)
  File "/MAGNN-master/utils/tools.py", line 72, in parse_adjlist
    num = len(edge_metapath_indices[0][0])
IndexError: index 0 is out of bounds for axis 0 with size 0
```

I think maybe it's because the code restrict that any node on any meta-path should have neighbors. Could you give me some advice how to fix it?

**Comment by cynricfu** [comment]
Each node of interest (e.g., the author nodes in the DBLP dataset) should be present in at least one metapath instance for every metapath.
To fix the relevant issue, the simplest way is to perform some data preprocessing to filter out the nodes that do not satisfy this requirement.

**Comment by empty-id** [comment]
OK, I get it.
