### ISSUE TITLE
How to perform link prediction (user-artist pair on Last.fm) for homogeneous methods like LINE and GCN?

### ISSUE THREAD

**Issue by kepsail** [cynricfu/MAGNN#18]
Hi, we appreciate your work.
I am confused about how to perform link prediction for  homogeneous methods like LINE, node2vec, GCN and GAT. They can only learn homogeneous graphs, i.e. they can only learn one type of object embedding, but the user-artist links in Last.fm are heterogeneous, which connect two different types of objects. As well, HAN is only able to learn the embeddings for one type of target objects.
Thanks.

**Comment by cynricfu** [comment]
As introduced in the paper, LINE and node2vec would treat all nodes of different types as one node type, thus ignoring the heterogeneity of graph structure.
GCN and GAT would operate on the metapath-based homogeneous graphs, and report the result of the best metapath combination. E.g., one may use UAU metapath to obtain user embeddings, and ATA metapath to obtain artist embeddings.
HAN would be trained in a similar way as GCN and GAT, but utilizing multiple metapaths at the same time.

All of these methods use the dot product as a decoder to get plausibility scores of user-artist pairs.

**Comment by kepsail** [comment]
Thank you for help
