### ISSUE TITLE
The preprocessing in DBLP,   shows Memory out ?

### ISSUE THREAD

**Issue by zhailiang041219** [cynricfu/MAGNN#19]
Thank you very much for your sharing the code.
I have a question about the prepeocessing in DBLP.  I used the **_preprocess_DBLP.ipynb_** to get the **_DBLP_processed_** file. But , it   took a long tim and shows  memory out error while processing the data. The laptop I use has 16 G  RAM. 
I wonder if my laptop RAM is low, or i have other mistakes in processing the data? How much memory of the RAM do you used to process DBLP dataset?
Looking forward to your reply.Thank you .

**Comment by kepsail** [comment]
I have the same problem. The preprocess requires large amount of resource and time.

**Comment by cynricfu** [comment]
The preprocessing codes are single-threaded programs. I believe they can be optimized using multiprocessing of Python.
As for the memory usage, I don't remember the exact number, but it should be large. Consider using a high-performance computing server to do this kind of job.

**Comment by zhailiang041219** [comment]
Thank you very much for your advice, I will try  multiprocessing of python .
