### ISSUE TITLE
Where do you get the metadata?

### ISSUE THREAD

**Issue by lighteningzhang** [cynricfu/MAGNN#2]
I would like to ask where do you get these three metadata. Thank you very much!

**Comment by cynricfu** [comment]
The IMDb and DBLP datasets are obtained from [the HAN repository](https://github.com/Jhy1993/HAN).
The Last.fm dataset is obtained from HetRec 2011: [https://grouplens.org/datasets/hetrec-2011/](https://grouplens.org/datasets/hetrec-2011/).
