### ISSUE TITLE
Could you publish the code of the baseline?

### ISSUE THREAD

**Issue by zezhishao** [cynricfu/MAGNN#20]
Hi, 
I am doing some tests on some baselines, such as GAT and GCN, on the preprocessed DBLP dataset. 
I am using metapath `APCPA` to construct a metapath-based homogeneous graph and conduct a GAT layer on it with the hyperparameter settings reported in MAGNN. 
But I got very different result, showing:
```shell
SVM test
Macro-F1: 0.938165~0.004259 (0.8), 0.937600~0.004730 (0.6), 0.937070~0.002117 (0.4), 0.933790~0.003152 (0.2)
Micro-F1: 0.942638~0.004183 (0.8), 0.942210~0.004119 (0.6), 0.941688~0.002020 (0.4), 0.938910~0.003140 (0.2)
K-means test
NMI: 0.778665~0.000000
ARI: 0.837312~0.000000
```
I think that this is because some how I introduced extra information that should not be involved and it makes the result higher, so I wonder that if the code for Baseline is available? 
I would be very appreciate if you could share the code of baslines! 👍 :)

**Comment by Wentao-Xu** [comment]
I also have a similar observation. The GAT has a much higher performance than the results reported in this paper.

Could you share the code of baselines? or a part of the baselines? Thank you very much.

**Comment by zezhishao** [comment]
@Wentao-Xu Sorry to reply so late, my implementation is to delete MetaPath Fusion and Metapath Encoding in accordance with the MAGNN framework, and implement a simple GAT.
I recently saw a KDD'21 paper that may answer this question: 
[Are we really making much progress? Revisiting, benchmarking, and refining heterogeneous graph neural networks](https://dl.acm.org/doi/10.1145/3447548.3467350)

**Comment by cynricfu** [comment]
In my original experiments, I tried homogeneous GNNs with (1) the original graph data without node/edge type information and (2) the metapath-based homogeneous graph constructed by the best-performing metapath.

On IMDb, (1) performs better. On DBLP, (2) performs better. The reported results on the paper are obtained with (2).

MAGNN without metapath fusion and metapath instance encoder is still not exactly the same as GAT using metapath-based homogeneous graphs. The metapath instances essentially provide prior weights on the metapath-based neighbors.
