### ISSUE TITLE
I have a question about the model

### ISSUE THREAD

**Issue by PArkJonGMin0704** [cynricfu/MAGNN#22]
What is the difference MAGNN_nc_mb.py and MAGNN_nc.py and MAGNN_lp.py?

**Comment by cynricfu** [comment]
`nc` means node classification.
`lp` means link prediction.
`MAGNN_nc.py` is for whole-batch training, supporting multiple layers.
`MAGNN_nc_mb.py` is for mini-batched training, currently does only support a single layer.

**Comment by PArkJonGMin0704** [comment]
thank you for your answer :)

**Comment by PArkJonGMin0704** [comment]
i have a one more question. How can i get the number of meta-path instance in code?

**Comment by cynricfu** [comment]
It should be doable, you may get the number of metapath instances by modifying the data loading functions.
