### ISSUE TITLE
I have a question about the Params

### ISSUE THREAD

**Issue by Ydongling** [cynricfu/MAGNN#24]
What do etypes_lists ，use_masks，use_masks mean？

**Comment by Clock966** [comment]
> What do etypes_lists ，use_masks，use_masks mean？

Do you know what etypes_lists means now?

**Comment by cynricfu** [comment]
For `etypes_lists`, please refer to #5 .

`use_masks` is for solving the data leakage problem as introduced in [this paper](https://arxiv.org/pdf/1905.13129.pdf). When constructing the subgraph for generating the target nodes (e.g., user A and artist B) embeddings, we need to remove the edge between A and B to avoid leaking prediction label to the training input. So `use_masks` is for indicating which metapath we should be careful about to avoid this problem, that is UAU, UATAU, AUA, AUUA metapaths in LastFM.

`no_masks` is just indicating do not try to avoid this issue.
