### ISSUE TITLE
Where can I download DBLP4057_GAT_with_idx.mat from?

### ISSUE THREAD

**Issue by sindhura97** [cynricfu/MAGNN#25]
This file is used in preprocess_DBLP.ipynb and I can't get it from the referenced repo. The referenced repo https://github.com/Jhy1993/HAN has a link to preprocessed DBLP but the link takes me to a website and I m not sure how to download DBLP4057_GAT_with_idx.mat from baidu while being in the US.

**Comment by cynricfu** [comment]
You may download `DBLP4057_GAT_with_idx.mat` through the following Dropbox share link:
[Dropbox Link](https://www.dropbox.com/s/fsq4vrazctna9w3/DBLP4057_GAT_with_idx.mat?dl=0)
