### ISSUE TITLE
what is the meaning of 'use_masks' and 'no_masks'?

### ISSUE THREAD

**Issue by hhmy27** [cynricfu/MAGNN#28]
Thanks for opening the source code

I'm confused about the code in **run_LastFM.py**

https://github.com/cynricfu/MAGNN/blob/b8557f58ae04a7fe3e7a9fde64ea87c81b331efe/run_LastFM.py#L21-L23

what is the meaning of 'use_masks' and 'no_masks'?

it's parameter in `parse_adjlist_LastFM`
https://github.com/cynricfu/MAGNN/blob/b8557f58ae04a7fe3e7a9fde64ea87c81b331efe/utils/tools.py#L129

Looking forward to your recovery

**Comment by cynricfu** [comment]
`use_masks` is for solving the data leakage problem as introduced in [this paper](https://arxiv.org/pdf/1905.13129.pdf). When constructing the subgraph for generating the target nodes (e.g., user A and artist B) embeddings, we need to remove the edge between A and B to avoid leaking prediction label to the training input. So `use_masks` is for indicating which metapath we should be careful about to avoid this problem, that is UAU, UATAU, AUA, AUUA metapaths in LastFM.

`no_masks` is just indicating do not try to avoid this issue.

**Comment by CoraHub** [comment]
Hi, I have a question on how to generate  train_val_test_idx.npz in prepeocess_LastFM.

**Comment by cynricfu** [comment]
> Hi, I have a question on how to generate train_val_test_idx.npz in prepeocess_LastFM.

Basically, `train_val_test_idx.npz` is generated by randomly sampling the user-artist pairs, with the rule that each user/artist should have one incident edge present in the training set.
