### ISSUE TITLE
id偏移问题请教

### ISSUE THREAD

**Issue by zuoxijunxifu** [cynricfu/MAGNN#29]
在FM数据集处理时，user和artist在处理流程和采样流程中反复进行偏移，为什么不把user和artist和其它节点统一编码，从头到尾一个节点只有唯一的id呢

**Comment by zuoxijunxifu** [comment]
在FM数据集处理时，user和artist在处理流程和采样流程中反复进行偏移，为什么不把user和artist和其它节点统一编码，从头到尾一个节点只有唯一的id呢

**Comment by cynricfu** [comment]
global ID 和 type-specific ID 在处理数据时各有各的好处，只使用统一的 global ID 当然也是可以的。
