### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by clz1314tyn** [cynricfu/MAGNN#30]
Hi, what is the reason for the memory error in the process of debugging Last_FM preprocessing code?

**Comment by bisamlu** [comment]
hi，i have the same problem. Have you solved it

**Comment by clz1314tyn** [comment]
> hi，i have the same problem. Have you solved it

I finally found that one of the nodes had too many connections, which reached the storage limit of List and NumPy in python, so the data set needs to be reduced.

**Comment by bisamlu** [comment]
> > hi，i have the same problem. Have you solved it
> 
> I finally found that one of the nodes had too many connections, which reached the storage limit of List and NumPy in python, so the data set needs to be reduced.

Thank you very much for your reply. I'll try it
