### ISSUE TITLE
About the graph embedding baselines

### ISSUE THREAD

**Issue by HjZ1998** [cynricfu/MAGNN#36]
Thanks for sharing the code! I am very interested in your experimental scheme! I encountered some problems with the HERec method's link prediction implementation during the implementation, so I was wondering if you could share your code for implementing data preprocessing and models under this task. Looking forward to your reply and tips!

**Comment by cynricfu** [comment]
We just used the code from the official repository of HERec, specifically [here](https://github.com/librahu/HERec/blob/master/code/HERec_spl.py).
Basically, just (1) apply DeepWalk to the metapath-based graphs to obtain metapath-specific embeddings, and then (2) employ the HERec official code above to fuse them and conduct rating/link prediction.
