### ISSUE TITLE
How can I modify the code so that only MAGNN is used to get the node embedding representation

### ISSUE THREAD

**Issue by Yuruzu** [cynricfu/MAGNN#37]
Thanks for sharing the code, I would like to use the MAGNN graph embedding algorithm to get the embedded representation of the nodes, and then do the follow-up work with other models. When I use base_MAGNN.py, do I also need to process the data into the form of your preprocessing? Could you please give me some ideas? Thank you

**Comment by cynricfu** [comment]
You would need to preprocess your data in a way similar to our preprocessing code. Then you can apply MAGNN to train upon your data, using MAGNN_nc for node classification or MAGNN_lp for link prediction. Finally, you may use the trained model to obtain the node representations.
