### ISSUE TITLE
how to preprocess dblp dataset?

### ISSUE THREAD

**Issue by midsummer08** [cynricfu/MAGNN#38]
thank you for your work,I am completing a system using MAGCN, so I would like to know how to preprocess the xml file of dblp to process the xml file into multiple matrices including features.

**Comment by cynricfu** [comment]
MAGNN preprocesses the DBLP dataset provided by the following paper. The provided dataset is in txt format. We do not know how to preprocess the original dataset in XML format from the DBLP website.

[Ming Ji](https://dblp.uni-trier.de/pid/15/1412.html), [Yizhou Sun](https://dblp.uni-trier.de/pid/37/3868.html), [Marina Danilevsky](https://dblp.uni-trier.de/pid/22/8355.html), [Jiawei Han](https://dblp.uni-trier.de/pid/h/JiaweiHan.html), [Jing Gao](https://dblp.uni-trier.de/pid/67/4834-4.html):
Graph Regularized Transductive Classification on Heterogeneous Information Networks. [ECML/PKDD (1) 2010](https://dblp.uni-trier.de/db/conf/pkdd/pkdd2010-1.html#JiSDHG10): 570-586
