### ISSUE TITLE
How to set parameter to achieve the result in the paper

### ISSUE THREAD

**Issue by Song-xx** [cynricfu/MAGNN#39]
I run the code of IMDB with default parameter with repeat=10, the result is good,but not as good as in the paper. how i can get the result as good as in the paper?

**Comment by cynricfu** [comment]
How does the model perform in your experiments? It should be expected if there are only slight variations.
The experimental results may depend on various factors, hyperparameters, package versions, CUDA versions, or hardware. After all, this is a model implemented three years ago. There could be some major changes/bug fixes in packages/hardware that could lead to different experimental results.

In addition, note that in `run_IMDB.py`, the default `patience` is set as `10`, whereas it is `30` in the paper. Changing this hyperparameter could help improve the performance.

**Comment by Song-xx** [comment]
> How does the model perform in your experiments? It should be expected if there are only slight variations. The experimental results may depend on various factors, hyperparameters, package versions, CUDA versions, or hardware. After all, this is a model implemented three years ago. There could be some major changes/bug fixes in packages/hardware that could lead to different experimental results.
> 
> In addition, note that in `run_IMDB.py`, the default `patience` is set as `10`, whereas it is `30` in the paper. Changing this hyperparameter could help improve the performance.

I use more repeat and get the result in the paper,even better. thanks

**Comment by ghost** [comment]
Then what CUDA version did you run to run this code?
