### ISSUE TITLE
Why is the edge from dst to src in DGL graph?

### ISSUE THREAD

**Issue by zezhishao** [cynricfu/MAGNN#4]
Hi~ I have a question when cosntructing the DGL graph.

https://github.com/cynricfu/MAGNN/blob/144f39a79c9e753cc3ff01ce680d00c46f407898/utils/tools.py#L97
According to the preprocessing code mentioned above in `parse_adjlist(adjlist, edge_metapath_indices, samples=None)`, elements in edges[i] should be (src, dst). But when constructing the DGL graph, it seems that you add an edge from dst to src.

https://github.com/cynricfu/MAGNN/blob/144f39a79c9e753cc3ff01ce680d00c46f407898/utils/tools.py#L116

I don’t quite understand this. Could you tell me something about that? Thank you very much!

**Comment by cynricfu** [comment]
For example, if we have a graph with 3 nodes [0, 1, 2] and edges [(0, 1), (0, 2), (1, 0), (2, 0)]
If we sample node 0 as the target node for graph convolution, parse_minibatch would firstly fetch the adjlist of node 0, that is [(0, 1), (0, 2)]
In DGL, the natural way to do graph convolution is to let message flow from the source nodes to the target node. So here I reverse the node pairs to be [(1, 0), (2, 0)] to let message flow from node 1 and node 2 to node 0.

**Comment by zezhishao** [comment]
Thanks for your reply! I think I understand.

But I still want to confirm whether the basis of this operation is that the relationship between the two nodes of DBLP is always bidirectional. (e.g., write vs. written by)

For example, in the graph [(0, 1), (0, 2), (1, 0)], the relationship between nodes is not always bidirectional, so when updating the target node 0, the extracted edge should be [(1,0)] instead of [(1,0),(2,0)].

Is this understanding correct?

**Comment by cynricfu** [comment]
Yes, in my preprocessing and model, each relationship between two nodes is converted to two directional edges. E.g., "A writes B" would be treated as "A writes B" and "B is written by A".

**Comment by zezhishao** [comment]
ok, thank you very much!
