### ISSUE TITLE
OOM kill 

### ISSUE THREAD

**Issue by knightzhong** [cynricfu/MAGNN#41]
Thanks for sharing the code! When I use other nodes in the DBLP dataset for preprocessing to search for meta path instances, such as some operations like the preprocess_DBLP.ipynb file. But it has always required a large amount of memory. Do the author know the reason for this?

**Comment by cynricfu** [comment]
Yes. `preprocess_DBLP.ipynb` does require a large amount of memory. You may just download and use the preprocessed dataset. Or you can revise the `get_metapath_neighbor_pairs` function to do some sub-sampling and reduce the dataset
