### ISSUE TITLE
what does etype_list mean?

### ISSUE THREAD

**Issue by chengchuncc** [cynricfu/MAGNN#42]
when I run the run_DBLP, I am confused what does "etypes_list = [[0, 1], [0, 2, 3, 1], [0, 4, 5, 1]]" mean. 
I see the closed question #5. But I also want to know where the code define the edge index number.

**Comment by cynricfu** [comment]
It is kind of hard-coded following some rules.
For DBLP, the node types `author`, `paper`, `term`, `conference` are indexed as `0`, `1`, `2`, `3`, respectively, as in [preprocess_DBLP.ipynb](https://github.com/cynricfu/MAGNN/blob/master/preprocess_DBLP.ipynb). Therefore, the edge types are indexed as below following the order.
`0` represents `author-paper`
`1` represents `paper-author`
`2` represents `paper-term`
`3` represents `term-paper`
`4` represents `paper-conference`
`5` represents `conference-paper`
