### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by wangsj12138** [cynricfu/MAGNN#46]
NMI: 0.044030~0.000000
ARI: -0.002919~0.000000
----------------------------------------------------------------
SVM tests summary
Macro-F1: 0.225872~0.055853 (0.8), 0.190818~0.025660 (0.6), 0.181179~0.010071 (0.4), 0.172284~0.026592 (0.2)
Micro-F1: 0.529167~0.096914 (0.8), 0.508333~0.043899 (0.6), 0.516667~0.029659 (0.4), 0.469792~0.090745 (0.2)
K-means tests summary
NMI: 0.044030~0.000000
ARI: -0.002919~0.000000
I ran this on a dblp subgraph I got myself. Is this normal? What should normal look like? Maybe there is something wrong? Thanks for your answer.

**Comment by cynricfu** [comment]
Can other models achieve normal performance on your extracted subgraph? You may also need to check if you properly run the MAGNN preprocessing code on your subgraph.
