### ISSUE TITLE
Lastfm dataset preprocess error

### ISSUE THREAD

**Issue by TMLOG** [cynricfu/MAGNN#8]
when I ran the preprocess_LastFM.ipynb to process the dataset for link prediction, there was something wrong.

![image](https://user-images.githubusercontent.com/70834990/94365536-69b68b80-0104-11eb-9570-57b7bf456dc3.png)

I coundn't find how to produce the ''data/preprocessed/LastFM_processed/user_artist.npy''  in the codes. Please help me with the problem.

**Comment by cynricfu** [comment]
Fixed, please check out the latest commit.

**Comment by TMLOG** [comment]
Thank you very much!
